FROM microsoft/aspnetcore-build:2.0.0-nanoserver AS builder
ENV ASPNETCORE_URLS http://+:5000
RUN mkdir /app
WORKDIR /app
COPY app.csproj ./
RUN dotnet restore
COPY . .
RUN dotnet publish --output /app/ --configuration Release

FROM microsoft/aspnetcore:2.0.0-nanoserver
WORKDIR /app
COPY --from=builder /app .
EXPOSE 5000
CMD dotnet app.dll
